zero-os/0-orchestrator

templates/node.g8os/actions.py
templates/storage_cluster/actions.py
templates/storagepool/actions.py

Add initial implementation for storagepool

---

templates/ardb/actions.py
templates/ardb/config.yaml
templates/ardb/schema.capnp

Relies on the container service.
The commit was basically copied from here https://github.com/g8os/ays_template_g8os/blob/master/templates/ardb.g8os/actions.py

Ardb service

---

templates/filesystem/actions.py
templates/filesystem/schema.capnp
templates/fssnapshot/actions.py
templates/fssnapshot/config.yaml
templates/fssnapshot/schema.capnp
templates/storagepool/actions.py

Add filesystem and snapshots services

---

api/node/ContainerNIC.go
api/node/CreateContainer.go
api/node/EnumContainerNICStatus.go
api/node/node_api_CreateContainer.go
raml/types.raml
templates/container/actions.py
templates/container/config.yaml

Fixes for creating container

---

api/node/VDiskLink.go
api/node/node_api_DeleteVM.go
api/volume/volume_api_CreateNewVolume.go
templates/nbdserver/actions.py
templates/vm/actions.py
templates/volume/actions.py
templates/volume/schema.capnp

Fix params for vm create wait for nbdserver

---

templates/nbdserver/actions.py
templates/vm/actions.py

renama nbdservice and make and fix isrunning

---

api/node/node_api_DeleteVM.go
api/tools/ays.go

Handle deleteServiceByName resposne correctly

Return correct status code for vm delete

---

templates/vm/actions.py

Add pause/resume to vm actions

---

templates/vm/actions.py

When starting vm verify that nbdcontainer is up and running
Don't crash when install already ran before and vm is already running

Verify vm is started

---

templates/network.g8os/actions.py

Use the IP of the internet providing interface

---

api/node/node_api_CreateBridge.go
api/node/node_api_CreateContainer.go
api/node/node_api_CreateFilesystem.go
api/node/node_api_CreateSnapshot.go
api/node/node_api_CreateStoragePool.go
api/node/node_api_CreateVM.go
api/node/node_api_DeleteBridge.go
api/node/node_api_DeleteContainer.go
api/node/node_api_DeleteFilesystem.go
api/node/node_api_DeleteFilesystemSnapshot.go
api/node/node_api_DeleteStoragePool.go
api/node/node_api_DeleteVM.go
api/node/node_api_ExitZerotier.go
api/node/node_api_JoinZerotier.go
api/node/node_api_MigrateVM.go
api/node/node_api_RebootNode.go
api/node/node_api_RollbackFilesystemSnapshot.go
api/node/node_api_StartContainer.go
api/node/node_api_StopContainer.go
api/storagecluster/storageclusters_api_DeployNewCluster.go
api/storagecluster/storageclusters_api_KillCluster.go
api/tools/ays.go
api/tools/vm.go
api/vdisk/vdisk_api_CreateNewVdisk.go
api/vdisk/vdisk_api_DeleteVdisk.go

Make sure we always specify actor and service in our blueprints

---

api/vdisk/vdisk_api_ListVdisks.go

Fix vdisk list

---

templates/nbdserver/actions.py
templates/vdisk/actions.py
templates/vm/actions.py

Leverage g8os sal during vdisk/vm creation

---

templates/storage_cluster/actions.py

to allow getting the addr from the node service, adjustments
were made to use the from_ays method, to pass the service in the init
of the node object of the of the sal-client

adjustments to use the service from the client obj

---

api/node/node_api_CreateContainer.go
templates/container/actions.py

Fix container mounts

---

buildscripts/builder-blockstor.sh
buildscripts/builder-cloud-init-server.sh
buildscripts/builder-grid-api.sh
buildscripts/builder-ovs.sh
buildscripts/tools.sh

Do some refactor for ensuring go and lddcopy
Also add lib to copying ubuntu packages

Add buildscript for openvswitch

---

api/node/node_api_CreateContainer.go
api/tools/ays.go

Check if filesystem and storagepool exists in container create

---

api/node/BridgeCreate.go
api/node/BridgeCreateSetting.go
api/node/ContainerNIC.go
api/node/CreateContainer.go
api/node/FilesystemCreate.go
api/node/NicLink.go
api/node/StoragePoolCreate.go
api/node/VMCreate.go
api/node/VMMigrate.go
api/node/VMUpdate.go
api/node/ZerotierJoin.go
api/node/node_api.go
api/node/node_api_CreateSnapshot.go
api/node/node_api_UpdateVM.go
api/storagecluster/ClusterCreate.go
api/storagecluster/storageclusters_api.go
api/validators/validators.go
api/vdisk/VdiskCreate.go
api/vdisk/vdisks_api.go

- Add validation for all enums #170
- Add validation for any attribute in a post payload that is used as an ays service name #155
- Add validation for some BridgeCreate attributes #152

1.1.0 alpha validators

---

templates/nbdserver/actions.py
templates/vdisk/actions.py

Adapt copyvdisk to pass metadata ardb

Pass config to nbdserver instead of gridapi

---

templates/storage_cluster/actions.py

completed the kill cluster api call to remove ardb, containers and storagepool

---

templates/network.publicstorage/actions.py

Make sure we use public interface for storage on packet.net

---

templates/bootstrap.g8os/actions.py

Set hostname of nodes

---

api/node/ContainerNIC.go
api/validators/validators.go

if type is default , id can be empty else
id cannot be empty.
relates to issue #180

bug fix concerning the default value of nic id

---

templates/nbdserver/actions.py

New config for nbdserver

---

api/node/node_api_FileDelete.go

relates to issue #179 
and depends on PR https://github.com/g8os/go-client/pull/15

handled delete error if file not found

---

templates/network.g8os/actions.py
templates/node.g8os/actions.py

Fix g8os network

---

templates/storage_cluster/actions.py

relates to issue https://github.com/g8os/resourcepool/issues/175

adjustments to delete in kill cluster + extra check on node to diskvalue

---

api/node/node_api_GetDiskInfo.go

Do this even if actually a partition is mounted.

Use mountinfo to fill disk information

---

templates/vm/actions.py

Fix limitio for disks

---

templates/vm/actions.py

Do not reboot vm for cpu/mem changes

---

templates/vm/actions.py

relates to issue https://github.com/g8os/resourcepool/issues/215

bug fix in migrate vm

---

templates/storagepool/actions.py

Fix error formatter used

---

scripts/diskwiper.py
scripts/resourcepoolinfo.py

Add some helper scripts

---

buildscripts/builder-blockstor.sh
templates/nbdserver/actions.py
templates/vdisk/actions.py

Update blockstor flist and adapt vdisk creation

---

templates/nbdserver/actions.py

Update in nbdserver config

---

buildscripts/builder-blockstor.sh
buildscripts/builder-cloud-init-server.sh
buildscripts/tools.sh

Update to buildscripts

---

api/node/node_api_StartContainerJob.go
api/node/node_if.go
raml/api.raml

Move process create on container to jobs

---

templates/nbdserver/actions.py
templates/vm/actions.py

relates to issue https://github.com/g8os/resourcepool/issues/229

spwan one nbdserver per vm instead of one per vdisk

---

.travis.yml
test.sh
tests/reset_env.py

Add travis

---

api/node/DHCP.go
api/node/EnumHTTPType.go
api/node/GWCreate.go
api/node/GWHost.go
api/node/GWNIC.go
api/node/GWNICConfig.go
api/node/HTTPProxy.go
api/node/PortForward.go
api/node/node_api_CreateGW.go
api/node/node_api_ListGateways.go
raml/api.raml
raml/types.raml

also updated the html and ramls and the structs concerning gateway

added the gateway create and list apis

---

templates/nbdserver/actions.py

bug fix in nbd

---

templates/storagepool/actions.py

Fixes for updating storagepooldevices

---

templates/nbdserver/actions.py

Fix for ndbserver stop

---

templates/nbdserver/actions.py
templates/vm/actions.py

Fixes for vm updates add/remove disk

---

pyclient/setup.py

fix for https://github.com/g8os/resourcepool/issues/291

Add python-dateutil as requirement for pyclient

---

api/node/node_api_CreateGW.go
api/node/node_api_CreateGWForwards.go
api/node/node_api_DeleteGWForward.go
api/node/node_api_GetGWFWConfig.go
api/node/node_api_GetGWHTTPConfig.go
api/node/node_api_SetGWFWConfig.go
api/node/node_api_SetGWHTTPConfig.go
api/node/node_api_UpdateGateway.go
api/tools/connection.go
raml/api.raml
templates/gateway/actions.py
templates/gateway/schema.capnp

added advanced flag in gateway schema to prevent adjustments to the
config through ays after custom config has been uploaded

added advanced http and firewall config options to api

---

templates/bootstrap.g8os/actions.py

Fix for boostrap

---

templates/vm/actions.py

Fix old import in vm actions.py

---

api/node/GWCreate.go
templates/http/actions.py

Fix gw creation

---

api/node/node_api_CreateBridge.go

added check to see  if bridge already exists

---

raml/types.raml

Update gateway definition

---

api/node/GW.go
templates/nbdserver/actions.py
templates/vm/actions.py

Some cleanups

---

api/node/CloudInit.go
raml/types.raml
templates/cloudinit/actions.py

Use yaml for cloud-init format #338

---

templates/nbdserver/actions.py

delete tmp vdisk data when deleting the disk

---

templates/gateway/actions.py

update gw status at stop and start

---

scripts/installgrid.sh

add installing zerotier client to installgrid

---

templates/nbdserver/actions.py

Wait for unix socket to be listening instead of file exists

---

scripts/install-orchestrator.sh

Fix install-orchestrator

---

tests/README.md
tests/bd-performance.py

update restapiserver to orchestratorserver naming

---

docs/setup/setup.md
templates/vdisk/actions.py
templates/vm/actions.py

Use the correct key for the 0-disk flist

---

templates/firewall/actions.py

Do not do firewall config if we dont have both public/private network

---

templates/gateway/actions.py

Update gw flist name

---

templates/node.zero-os/actions.py

Do not monitor node if its not in installed state

---

api/node/node_api_StartContainerJob.go

relates to issue https://github.com/zero-os/0-orchestrator/issues/297

bug fix in start container job for env

---

api/storagecluster/storageclusters_api_KillCluster.go

Prevent storage cluster deletion if it has vdisks attached 

---

templates/configuration/actions.py

Validate config during processChange aswell

---

templates/gateway/actions.py

Do not compare cpanp data with dict and vice versa as this will always
return false.
Make sure we always assign dict not capnp to capnp

Gateway update: always compare on dict level

---

docs/setup/setup.md
templates/bootstrap.zero-os/actions.py
templates/bootstrap.zero-os/schema.capnp

Add flag to bootstrap to wipe new nodes their disks (#435)

---

templates/cloudinit/actions.py
templates/dhcp/actions.py
templates/firewall/actions.py
templates/gateway/actions.py

Wrong params where being passed to the update jobs

Fix update of gateway

---

api/tools/connection.go

Use ssl connection to zero-os

---

pyclient/zeroos/orchestrator/sal/Network.py
pyclient/zeroos/orchestrator/sal/Node.py
templates/network.switchless/actions.py
templates/network.switchless/schema.capnp

Add switchless networking

---

pyclient/zeroos/orchestrator/sal/ARDB.py

Open ardb ports when needed

---

tests/bd-performance.py

Raise the limit of the nbddevice to 512

---

docs/gateway/gateway.md
pyclient/zeroos/orchestrator/sal/gateway/cloudinit.py
pyclient/zeroos/orchestrator/sal/gateway/dhcp.py
pyclient/zeroos/orchestrator/sal/gateway/http.py
raml/types.raml
templates/gateway/actions.py
templates/http/actions.py
templates/storagepool/actions.py
templates/vm/actions.py

Make cloudinit use ec2 alike config which is faster and more compatible
Check on port of dhcp to check its running
Check on port of cloudinit to check if its running
Caddy required SIGUSR1 to restart not SIGHUB
VM should cleanup nbdserver at shutdown

Harderning of services

---

api/node/VMCreate.go
api/node/node_api_CreateVM.go
raml/types.raml
templates/vm/schema.capnp
templates/zerodisk/actions.py

Check on vm name conflict
Remove cloudinit config from vm this is done by gw now

Fixes in vm create

---

templates/gateway/actions.py

Copy cidr from the nic instead of from the config

---

api/node/ContainerNIC.go
api/node/GWNIC.go

ContainerNic base should be serialized inline

---

templates/vm/actions.py

Open and drop vnc ports for vm automatically

---

templates/vm/actions.py

urgent blocking 
relates to https://github.com/zero-os/0-orchestrator/issues/432#issuecomment-309712109

bug fix for vm create

---

templates/tlogserver/actions.py

 	Fix tlog start if already started

---

api/node/node_api_DeleteBridge.go
api/node/node_api_DeleteContainer.go
api/node/node_api_DeleteFilesystem.go
api/node/node_api_DeleteFilesystemSnapshot.go
api/node/node_api_DeleteGateway.go
api/node/node_api_DeleteNode.go
api/node/node_api_DeleteStoragePool.go
api/node/node_api_DeleteVM.go
api/node/node_api_ExitZerotier.go
api/node/node_api_JoinZerotier.go
api/node/node_api_StartContainer.go
api/node/node_api_StartGateway.go
api/node/node_api_StopContainer.go
api/node/node_api_StopGateway.go
api/storagecluster/storageclusters_api_KillCluster.go
api/tools/ays.go
api/tools/runs.go
api/vdisk/vdisk_api_DeleteVdisk.go

Make sure we check the status on new run object

---

.travis.yml

Add npm install

---

api/tools/oauth2_itsyouonline_middleware.go

Allow requests that are commming from the organization itself
See #531

Change JWT validation

---

api/tools/oauth2_itsyouonline_middleware.go

Return 440 when jwt is expired

---

scripts/install-orchestrator.sh

since AYS is not protected with jwt, we can't execute AYS command from
the install script

don't try to execute AYS command fom the installer

---

api/tools/connection.go

fix authorization header format

---

buildscripts/builder-redis.sh

Add redis buildscript

---

scripts/install-orchestrator.sh

used the zerotier-cli to get the ip instead
reltes to issue #547

removed hardcoding which refrences zertier interface

---

scripts/install-orchestrator.sh

relates to issue #546

---

templates/vm/actions.py

bug fix concerning vm create , passed jwt in client call

---

templates/vm/actions.py

Createvm issue565

---

pyclient/zeroos/orchestrator/sal/ARDB.py
templates/storage_cluster/actions.py
templates/tcp/actions.py
templates/tcp/config.yaml
templates/tcp/schema.capnp

Fix storage cluster resource conflict

---

scripts/install-orchestrator.sh

minor bug fix for spevific zerotier network check in install script

---

buildscripts/builder-0-statscollector.sh

Update stats while go get

---

api/tools/oauth2_itsyouonline_middleware.go
docs/api/README.md
pyclient/zeroos/orchestrator/client/oauth2_client_itsyouonline.py

Make sure the expiration date of the jwt token is not too long

Master jwt exp limit

---

pyclient/zeroos/orchestrator/sal/StoragePool.py

see https://github.com/zero-os/0-orchestrator/issues/629

recursively delete children first when deleting subvolume

---

pyclient/zeroos/orchestrator/configuration.py

Adds make the refreshed token valid for 1 hour only

---

pyclient/zeroos/orchestrator/sal/Container.py

Fix container create

---

templates/stats_collector/actions.py

Pass correct argument for token and set hostname of container

---

pyclient/zeroos/orchestrator/sal/templates/dashboards/overview.json
templates/statsdb/actions.py

Add grafana dashboard json

---

docs/setup/README.md
scripts/install-orchestrator.sh

Small doc update

---

pyclient/setup.py
pyclient/zeroos/orchestrator/sal/templates/dashboards/overview.json

Add dashboards to setup.py and fix dashboard refresh

---

templates/nbdserver/actions.py

Fix: Add slavestoragecluster if found to nbd config

---

pyclient/zeroos/orchestrator/sal/StoragePool.py
templates/storage_cluster/actions.py

Fix: dd devices to /dev instead of root, remove, drops tcp ports on storage cluster delete, fix storage pool deletion

---

buildscripts/builder-cockroachdb.sh

Implement buildscript for cockroachdb

---

buildscripts/builder-etcd.sh

Implement buildscript for etcd

---

templates/nbdserver/actions.py

Fix monitoring of nbdserver when status is halted

---

templates/nbdserver/actions.py

Fix monitoring of nbdserver when status is halted (#694)

---

templates/storage_cluster/actions.py

in cluster init  minimal dashboard and complete it in install

---

api/node/node_api_MigrateVM.go
templates/nbdserver/actions.py
templates/node.zero-os/actions.py
templates/storage_cluster/actions.py
templates/storagepool/actions.py
templates/vm/actions.py

**Done please review**
the implements the live vm migration throught libvirt and ssh and the move vm (dead migration)

Migrate vm

---

pyclient/zeroos/orchestrator/sal/Container.py
templates/etcd/actions.py
templates/etcd/config.yaml
templates/etcd/schema.capnp
templates/etcd_cluster/actions.py
templates/etcd_cluster/config.yaml
templates/etcd_cluster/schema.capnp
templates/storage_cluster/actions.py

relates to #680 
The approach taken here is 
- Like nodes should be passed through blueprint to the `etcd_cluster` service
- Deployment of one `etcd` server per node. Therefore, `size < #nodes` is not allowed
- If #nodes is larger than the size, random size number of nodes would be chosen and `etcd` servers would be deployed to those nodes.

Intial implementation of etcd cluster service

---

templates/etcd/actions.py
templates/etcd/config.yaml
templates/etcd_cluster/actions.py

add monitor action to etcd and Allow only odd size of etcd cluster

---

templates/etcd_cluster/actions.py

Prevent etcd cluster deploying if size is bigger than number of nodes

---

templates/vm/actions.py

https://docs.greenitglobe.com/openvcloud/openvcloud/issues/6

added code to setup network for vm migration

---

api/node/node_api_GetDashboard.go
raml/api.html
raml/types.raml

fix grafana get returns node name

---

templates/nbdserver/actions.py

update nbd config to the latest

---

pyclient/zeroos/orchestrator/sal/healthcheck.py

When an update is required we can just remove the container during the
update procedure and it will be created again

Let the healthcheck container live forever

---

pyclient/zeroos/orchestrator/sal/healthchecks/cpu_mem_core_check.py

harden cpu-mem health check

---

buildscripts/builder-healthcheck.sh

Adds healthcheck build  for the new flist

---

pyclient/zeroos/orchestrator/sal/healthcheck.py
pyclient/zeroos/orchestrator/sal/healthchecks/log_rotator.py
templates/node.zero-os/actions.py

Adds log rotator health check

---

api/healthcheck/HealthCheck.go
pyclient/zeroos/orchestrator/sal/healthchecks/cpu_mem_core_check.py
pyclient/zeroos/orchestrator/sal/healthchecks/openfiledescriptors.py
raml/types.raml
templates/node.zero-os/schema.capnp

Add catergory field in healthcheck

---

templates/node.zero-os/actions.py

Pass authentication to watchdog action

---

api/healthcheck/HealthCheck.go
raml/api.html
raml/types.raml
templates/node.zero-os/actions.py
templates/node.zero-os/schema.capnp

Adds healthcheck lastruntime and interval

---

templates/node.zero-os/actions.py

Fix node authentication

---

api/tools/http.go
templates/vm/actions.py

also  added a condition in the handle ays error to handle errors with no
reponse body from ays
this is dependant on https://github.com/zero-os/0-core/pull/436 , do not merge until that is done

adjusted the way the prepare migration is used to fit new client

---

templates/vm/actions.py

Fix vm restarting after stopping the vm

---

pyclient/zeroos/orchestrator/sal/healthcheck.py
pyclient/zeroos/orchestrator/sal/healthchecks/networkbond.py
templates/node.zero-os/actions.py

Add bonding check + exception protection

---

pyclient/zeroos/orchestrator/sal/healthcheck.py
pyclient/zeroos/orchestrator/sal/healthchecks/cpu_mem_core.py
pyclient/zeroos/orchestrator/sal/healthchecks/interrupts.py
pyclient/zeroos/orchestrator/sal/healthchecks/log_rotator.py
pyclient/zeroos/orchestrator/sal/healthchecks/networkbond.py
pyclient/zeroos/orchestrator/sal/healthchecks/openfiledescriptors.py
pyclient/zeroos/orchestrator/sal/healthchecks/temperature.py

Add constructor to HealthCheckRun
Add method add_message
This will prevent bogus messages to be send

Refactor healthchecks

---

pyclient/zeroos/orchestrator/sal/healthcheck.py
pyclient/zeroos/orchestrator/sal/healthchecks/powersupply.py
templates/node.zero-os/actions.py

Adds power supply health check

---

pyclient/zeroos/orchestrator/sal/healthcheck.py
pyclient/zeroos/orchestrator/sal/healthchecks/fan.py
templates/node.zero-os/actions.py

Adds fan health check

---

pyclient/zeroos/orchestrator/sal/healthcheck.py
pyclient/zeroos/orchestrator/sal/healthchecks/openfiledescriptors.py

Make sure params of healtcheck are correct type

---

templates/node.zero-os/actions.py

removed duplicate code that causes monitor to error

---

api/vendor/github.com/zero-os/0-core/client/go-client/client.go
api/vendor/github.com/zero-os/0-core/client/go-client/container.go
api/vendor/github.com/zero-os/0-core/client/go-client/options.go

Update zero-os go client

---

pyclient/zeroos/orchestrator/sal/healthchecks/cpu_mem_core.py
pyclient/zeroos/orchestrator/sal/healthchecks/fan.py
pyclient/zeroos/orchestrator/sal/healthchecks/log_rotator.py
pyclient/zeroos/orchestrator/sal/healthchecks/networkbond.py
pyclient/zeroos/orchestrator/sal/healthchecks/openfiledescriptors.py
pyclient/zeroos/orchestrator/sal/healthchecks/powersupply.py
pyclient/zeroos/orchestrator/sal/healthchecks/temperature.py
pyclient/zeroos/orchestrator/sal/healthchecks/threads.py

use lowercase for healthcheck ids

---

pyclient/zeroos/orchestrator/sal/healthcheck.py
pyclient/zeroos/orchestrator/sal/healthchecks/fan.py
pyclient/zeroos/orchestrator/sal/healthchecks/powersupply.py
pyclient/zeroos/orchestrator/sal/healthchecks/temperature.py

Skip if no ipmi is found

---

pyclient/zeroos/orchestrator/sal/Node.py

Fix referenced before assignment

---

pyclient/zeroos/orchestrator/sal/healthchecks/cpu_mem_core.py

Adds fix to -1 in ids and a small fix to names

---

pyclient/zeroos/orchestrator/sal/healthcheck.py
pyclient/zeroos/orchestrator/sal/healthchecks/networkload.py
templates/node.zero-os/actions.py

Adds Network Load health check

---

pyclient/zeroos/orchestrator/sal/healthcheck.py
templates/node.zero-os/actions.py

Add healthcheck report for node status

---

pyclient/zeroos/orchestrator/sal/healthcheck.py
pyclient/zeroos/orchestrator/sal/healthchecks/ssh_cleanup.py
templates/node.zero-os/actions.py
templates/vm/actions.py

Adjusted code to allow the script to work easier
relates to issue #618

Added new self healing healthcheck for ssh deamon created in migrate

---

pyclient/zeroos/orchestrator/sal/StorageEngine.py
templates/node.zero-os/actions.py
templates/storage_engine/actions.py
templates/storage_engine/schema.capnp

Add ardb health check

---

pyclient/zeroos/orchestrator/sal/healthcheck.py
pyclient/zeroos/orchestrator/sal/healthchecks/qemu_vm_logs.py
pyclient/zeroos/orchestrator/sal/healthchecks/ssh_cleanup.py
templates/node.zero-os/actions.py

Added heath check to check on the logs located at /var/log/libvirt/qemu/(vmname).log and parse to check for errors to see status of vm within libvirt.
This relates to issue #606

added health check to check on libvirt's qemu vm logs

---

templates/node.zero-os/actions.py

Fix order of nodestatus healthcheck

---

pyclient/zeroos/orchestrator/sal/Pubsub.py
templates/node.zero-os/actions.py

Hardening of watchdog code

---

pyclient/zeroos/orchestrator/sal/healthchecks/networkload.py

Adds fix to network load health check

---

templates/vm/actions.py

if a parameter such as vdisk or nic is passed as empty it will remove the existing ones , if not passed at all in the blueprint it will remain
the same.

changed behaviour of process change in vm actions

---

pyclient/zeroos/orchestrator/sal/Pubsub.py
templates/node.zero-os/actions.py

Fix blpop call

---

pyclient/zeroos/orchestrator/sal/healthcheck.py
pyclient/zeroos/orchestrator/sal/healthchecks/diskusage.py
templates/node.zero-os/actions.py

diskusage healthcheck

---

templates/node.zero-os/actions.py

ensure that watchdog uses the service loop

---

api/node/Container.go
api/node/node_api_GetContainer.go

This is needed to be able to process the stats

Add containerid to getcontainer request

---

templates/vdisk/actions.py

Regression: Fix rollback

---

templates/nbdserver/actions.py
templates/tlogserver/actions.py

remove verbose from nbd and tlog servers

---

templates/nbdserver/actions.py

fix nbdserver watchdog handler after migration

---

pyclient/zeroos/orchestrator/sal/healthchecks/powersupply.py

Fixes powersupply id in message

---

templates/tcp/actions.py
templates/tcp/schema.capnp
templates/tlogserver/actions.py
templates/vdisk/actions.py

Fix tlog stop when it's not running

---

templates/vdisk/actions.py

remove templatevdiskid from vdisk static

---

api/healthcheck/health_api_Node.go
api/healthcheck/health_api_Nodes.go
templates/healthcheck/schema.capnp
templates/node.zero-os/actions.py
templates/node.zero-os/schema.capnp

Refactor healthchecks to their own service

---

templates/tlogserver/actions.py

fix droping/opening tlogserver

---

pyclient/setup.py

Fix python install of orchestrator

---

templates/vm/actions.py

Adds don't use one disk for many machines

---

pyclient/zeroos/orchestrator/sal/healthchecks/ssh_cleanup.py
templates/tlogserver/actions.py
templates/vm/actions.py

also adjusted the code to consume the tcp to allow clean up to detect it
afterwards

refactor the migration code to allow proper naming of nbd

---

api/node/GWCreate.go
templates/gateway/actions.py

Don't allow starting nic name with number when creating gateway

---

pyclient/setup.py

Add aioredis to setup.py

---

scripts/install-orchestrator.sh

Add install --core and --orchestrator branch optional argument

---

templates/container/actions.py

check if ovs is running before creating containers with vlan nics

---

scripts/install-orchestrator.sh

Improve argument handling and add summary during initializing

---

api/healthcheck/HealthCheck.go
api/healthcheck/health_api_StorageCluster.go
api/healthcheck/health_api_StorageClusters.go
api/healthcheck/healthcheck_if.go
pyclient/zeroos/orchestrator/client/EnumContainerListItemStatus.py
pyclient/zeroos/orchestrator/client/EnumContainerStatus.py
pyclient/zeroos/orchestrator/client/EnumVMListItemStatus.py
pyclient/zeroos/orchestrator/client/EnumVMStatus.py
pyclient/zeroos/orchestrator/client/Message.py
pyclient/zeroos/orchestrator/client/StorageClusterHealthCheck.py
pyclient/zeroos/orchestrator/client/health_service.py
raml/api.html
raml/api.raml
raml/types.raml
templates/storage_cluster/actions.py
templates/storage_cluster/config.yaml
templates/vdisk/schema.capnp

Disk orphans healthcheck

---

templates/tlogserver/actions.py

Fix starting vm with tlogserver

---

pyclient/zeroos/orchestrator/sal/grafana/grafana.py
templates/grafana/actions.py

grafana: support influxdb in process change

---

api/node/ContainerUpdate.go
api/node/node_api_UpdateContainer.go
api/node/node_if.go
raml/api.html
raml/api.raml
raml/types.raml
templates/container/actions.py

only available update through the client are the nics so that is what
was added,
relates to issue #765

added api for container update

---

templates/vdisk/actions.py

Fix referenced before assignment error if vdisk doesn't have a template

---

templates/bootstrap.zero-os/actions.py

ncreased timeout for the bootstrap of zerotier

---

templates/container/actions.py

Fixes getting node from ays with jwt

---

api/healthcheck/health_api_StorageCluster.go
templates/storage_cluster/actions.py

Orphan vdisk remove

---

pyclient/zeroos/orchestrator/sal/healthchecks/qemu_vm_logs.py

fixed qemu health check

---

api/generate.go

Dont run go-bin-data in debug mode

---

api/ays-client/Job.go
api/node/node_api_UpdateContainer.go
api/tools/ays.go
api/vendor/github.com/zero-os/0-core/client/go-client/container.go
templates/container/actions.py

handled error if vlan is passed without ovs container being available

---

templates/storage_cluster/actions.py
templates/tlogserver/actions.py
templates/vdisk/actions.py
templates/vm/actions.py

Use EtcdCluster put function instead of picking out a random etcd server

---

api/vdisk/Vdisk.go
api/vdisk/VdiskCreate.go
api/vdisk/VdiskListItem.go
api/vdisk/vdisk_api_CreateNewVdisk.go
api/vdisk/vdisk_api_ListVdisks.go
api/vdisk/vdisk_api_RollbackVdisk.go
pyclient/zeroos/orchestrator/client/Vdisk.py
pyclient/zeroos/orchestrator/client/VdiskCreate.py
pyclient/zeroos/orchestrator/client/VdiskListItem.py
raml/api.html
raml/types.raml
templates/tlogserver/actions.py
templates/vdisk/actions.py
templates/vdisk/schema.capnp

Change vdisk field storagecluster to blockstoragecluster

---

pyclient/zeroos/orchestrator/sal/healthchecks/networkstability.py

Improve parsing of networkstability

---

templates/gateway/actions.py
templates/gateway/schema.capnp

Adds backup and restore for caddy certificates

---

docs/setup/README.md
docs/setup/configuration.md

Change versioning docs to configuration, move iyo config keys to it

---

templates/storage_cluster/actions.py

Check if iyo configuration is valid when deploying object cluster

---

templates/storage_cluster/actions.py

minor refactor

---

api/tools/vm.go
templates/nbdserver/actions.py

also added code to make job search for nbd be more precise
relates to issue #898 the issue is fixed by https://github.com/zero-os/0-core/pull/485, this is just clean up

adjusted code to wait for vm actions

---

pyclient/zeroos/orchestrator/sal/StoragePool.py

adjusted delete storage pool to remove all related partitions

---

templates/vdisk/actions.py

Rollback fix

---

pyclient/zeroos/orchestrator/sal/Node.py

When passing wipedisks param to the node dont wipe usb disks
See: #929

Do not wipe usb disks

---

templates/node.zero-os/actions.py

Subscribe only if it wasn't subscribed before

---

scripts/install-orchestrator.sh

Prevent shift if no params inserted

---

templates/vdisk/actions.py

Fix choosing random node if halted

---

templates/vm/actions.py

Call migrate action directly within the service

---

templates/vm/actions.py

cleaning up after vm shutdown shouldn't be part of its timeout

---

docs/setup/README.md
docs/setup/configuration.md
templates/storage_cluster/actions.py
tests/0_orchestrator/enable_jwt.sh

Refactor variables:
```
- iyo_org -> 0-stor-organization
- iyo_namespace -> 0-stor-namespace
- iyo_clientID -> 0-stor-clientid
- iyo_secret -> 0-stor-clientsecret
```

Refactor 0-stor variables name (iyo_org, iyo_namespace, ...)

---

raml/api.html
raml/types.raml

fix api.html

---

pyclient/zeroos/orchestrator/sal/Container.py
pyclient/zeroos/orchestrator/sal/ETCD.py
pyclient/zeroos/orchestrator/sal/StorageCluster.py
pyclient/zeroos/orchestrator/sal/StorageEngine.py
templates/backup.container/actions.py
templates/cloudinit/actions.py
templates/container/actions.py
templates/dhcp/actions.py
templates/etcd/actions.py
templates/etcd_cluster/actions.py
templates/firewall/actions.py
templates/gateway/actions.py
templates/grafana/actions.py
templates/http/actions.py
templates/influxdb/actions.py
templates/nbdserver/actions.py
templates/network.switchless/actions.py
templates/network.zero-os/actions.py
templates/stats_collector/actions.py
templates/tlogserver/actions.py
templates/vm/actions.py

* bug fix for etcd_cluster
the running status was not set at the end of the watchdog handler
so the code returned everytime after the first.
* adjusted code to delete etcd services after deploy
to avoid issue code exiting
* added ays logger in the sals for consistency
- added and optional param of logger to allow usage of ays logger instead
of default logger for consistant logs
- removed uneccessary code
- added the running status to etcd_cluster after the cluster is done
with all actions of recovering to ensure no race conditions occur
* etcd cluster handling new scenarios
- in disaster mode  added code that removes data-dir to avoid cached
configs
- sperated code into functions to allow reuse to check on containers
being stopped or deleted
* code adjustments for cleaner code

Etcd cluster bug (#1004)

---

api/tools/ays.go
api/tools/runs.go
pyclient/zeroos/orchestrator/utils.py
templates/container/actions.py
templates/vm/actions.py

this relates to issue https://github.com/zero-os/0-orchestrator/issues/1006
this depends on PR https://github.com/zero-os/0-core/pull/501

more handling for core0 error to proppagate to api

---

templates/node.zero-os/actions.py

Check if not running asyncronously instead of calling the monitor action

---

templates/vdisk/actions.py

WIP: Vdisk rollback

---

pyclient/zeroos/orchestrator/sal/gateway/http.py
templates/http/actions.py

Fix monitoring for http service

---

templates/configuration/actions.py
templates/storage_cluster/actions.py

moved the validation code into the config service instead of the storage
cluster creation
relates to issue #1017

moved validation code into the config service

---

api/tools/ays.go
api/tools/http.go

handled empty result error on job
relates to #1044

handled non http responses from ays

---

api/validators/validators.go

Check if vdisk blocksize is a power of 2

---

templates/storage_cluster/actions.py

Fix aqcuiring disks if metadisks and datadisks are of different types

---

templates/vdisk/actions.py

Increase timeout for vdisk install and rollback

---

pyclient/zeroos/orchestrator/sal/ZeroStor.py

Remove interface param to zerostor

---

pyclient/zeroos/orchestrator/sal/healthchecks/interrupts.py

Increase threshold for interrupts

---

pyclient/zeroos/orchestrator/sal/Container.py

Add name to container info

---

autosetup/autobootstrap.py

Adapt autosetup to newly changes

---

api/tools/connection.go
autosetup/autobootstrap.py

Fix direct access calls using jwt

---

templates/filesystem/actions.py

Fix minor error

---

api/validators/validators.go
pyclient/zeroos/orchestrator/sal/Container.py
templates/vdisk/actions.py

Use subscribe/stream instead of wait/timeout for vdisk jobs

---

templates/storage_cluster/actions.py
templates/storage_cluster/config.yaml
templates/vdisk/config.yaml

- Fix agrnames in vdisk config.
- Adapt storage_cluster and etcd_cluster relationship to the new ays version

Minor fixes

---

api/ays-client/AYSRun.go
api/ays-client/AysRepositoryRepositoryBlueprintBlueprintPostReqBody.go
api/ays-client/JobData.go
api/node/BaseNic.go
api/node/ContainerUpdate.go
api/node/CreateContainer.go
api/node/GW.go
api/node/GWCreate.go
api/node/GWNIC.go
api/node/NicLink.go
api/node/VMCreate.go
api/node/VMUpdate.go
api/node/node_api_CreateContainer.go
api/node/node_api_CreateGW.go
api/node/node_api_CreateVM.go
api/node/node_api_UpdateContainer.go
api/node/node_api_UpdateGateway.go
api/node/node_api_UpdateVM.go
api/tools/ays.go
api/tools/runs.go

- Refactor waitrundone to wait until all ays retries are done before returning the run.
- Refactor nic validation across container/vm/gateway apis.

Wait on run

---

templates/storage_cluster/actions.py

add disk type to the error message

---

api/backup/backup_api.go
api/graph/graph_api.go
api/healthcheck/healthcheck_api.go
api/main.go
api/node/node_api.go
api/router/router.go
api/storagecluster/storageclusters_api.go
api/tools/connection.go
api/tools/jwt.go
api/tools/oauth2_itsyouonline_middleware.go
api/vdisk/vdisks_api.go

Also improved how jwt's are refreshed into 1 instance, instead of 1 per api section

Replaced clientid & secret parameters with jwt

---

api/main.go
api/tools/jwt.go

Add development mode to the api

---

api/storagecluster/ClusterCreate.go
api/storagecluster/storageclusters_api_DeployNewCluster.go
api/validators/validators.go
pyclient/zeroos/orchestrator/client/ClusterCreate.py
raml/api.html
raml/types.raml
templates/storage_cluster/actions.py
templates/storage_cluster/schema.capnp

Disks per storserver

---

templates/storage_cluster/actions.py

The check below it, does the intented job

Remove bad check

---

templates/storage_cluster/actions.py

Remove bad check (#1142)

---

templates/storage_engine/schema.capnp
tests/0_orchestrator/test_suite/testcases/advanced_tests/test01_containers_apis.py
tests/0_orchestrator/test_suite/testcases/basic_tests/test03_containers_apis.py

related to tasks
- https://github.com/gig-projects/org_quality/issues/676
- https://github.com/gig-projects/org_quality/issues/675
- https://github.com/gig-projects/org_quality/issues/657
- https://github.com/gig-projects/org_quality/issues/653

add testcases to containers testsuites

---

pyclient/zeroos/orchestrator/sal/ZeroStor.py
templates/storage_cluster/actions.py
templates/zerostor/schema.capnp

Add missing zerostor config

---

templates/storage_engine/actions.py

 race condition: fix watchdog from restarting a halted ardb

---

tests/0_orchestrator/test_suite/testcases/basic_tests/test07_vms_apis.py

related to
https://github.com/zero-os/0-orchestrator/issues/1180

implementation of task #1180" testcase

---

pyclient/zeroos/orchestrator/sal/ETCD.py
templates/storage_engine/actions.py
templates/storagecluster.block/actions.py
templates/storagecluster.object/actions.py

prevent watchdog to perform undeeded restart to servers

---

templates/storagecluster.block/actions.py
templates/storagecluster.object/actions.py

delete filesystems when deleting storagecluster

---

pyclient/zeroos/orchestrator/sal/abstracts.py

remove storagepool after unmount

---

templates/etcd_cluster/actions.py

remove sync in etcd_cluster

---

api/node/node_api_MigrateVM.go

use update blueprint in vmmigrate

---

api/node/node_api_MigrateVM.go
tests/0_orchestrator/test_suite/framework/orchestrator_apis/containers_apis.py
tests/0_orchestrator/test_suite/testcases/basic_tests/test03_containers_apis.py
tests/0_orchestrator/test_suite/testcases/basic_tests/test10_containers_apis_ext.py

fixes https://github.com/gig-projects/org_quality/issues/674

cover new apis in containers

---

.travis.yml
tests/0_orchestrator/test_suite/testcases/testcases_base.py

This method will allow you to add your github ssh to any vm through the vnc protocol. You have to create a zt nw, Join this zt, Create a vm and call this method.

add ssh key to vm

---

templates/storagecluster.object/actions.py

use schemas config for object cluster

---

pyclient/zeroos/orchestrator/sal/StorageCluster.py
templates/node.zero-os/actions.py

Get disk fix

---

pyclient/zeroos/orchestrator/sal/StorageCluster.py
pyclient/zeroos/orchestrator/sal/StorageEngine.py
pyclient/zeroos/orchestrator/sal/StoragePool.py
pyclient/zeroos/orchestrator/sal/grafana/grafana.py
templates/dashboard/actions.py
templates/grafana/actions.py
templates/influxdb/actions.py
templates/stats_collector/actions.py
templates/statsdb/actions.py

Cluster dashboard

---

api/node/GW.go
api/node/node_api_MigrateGW.go
api/node/node_if.go
raml/api.html
raml/api.raml
raml/types.raml
templates/gateway/actions.py

Fixes #1132 
Support migrating gateway to a different node

Master gateway migrate

---

templates/node.zero-os/actions.py

Filter only messages of level 20

---

api/node/ExportVM.go
api/node/node_api_ExportVM.go
api/node/node_api_ImportVM.go
api/storagecluster/Cluster.go
api/storagecluster/storageclusters_api_GetClusterInfo.go
api/validators/validators.go
raml/api.html
raml/api.raml
raml/types.raml
templates/vdisk/actions.py
templates/vdisk/schema.capnp
templates/vm/actions.py
templates/vm/schema.capnp

Import export vm

---

pyclient/zeroos/orchestrator/sal/Node.py
pyclient/zeroos/orchestrator/sal/StorageCluster.py
pyclient/zeroos/orchestrator/utils.py
templates/etcd_cluster/actions.py
templates/storagecluster.block/actions.py
templates/storagecluster.object/actions.py

it will search for NVME then SSD then will default to fscache whatever
that may be. do not handle using ready sp unless they are old etcd sp
created from before.
relates to issue #1016

etcd now will prioritize faster disks for its sp

---

tests/0_orchestrator/test_suite/testcases/basic_tests/test05_storagepools_apis.py

fixes https://github.com/zero-os/0-orchestrator/issues/1235

Remove storagepool last device testcase

---

.travis.yml
tests/0_orchestrator/test_suite/testcases/testcases_base.py

fixes https://github.com/zero-os/0-orchestrator/issues/1232

Tests logging

---

.travis.yml
tests/0_orchestrator/test_suite/config.ini
tests/0_orchestrator/test_suite/framework/orchestrator_apis/containers_apis.py
tests/0_orchestrator/test_suite/framework/orchestrator_apis/vdisks_apis.py
tests/0_orchestrator/test_suite/framework/orchestrator_apis/vms_apis.py
tests/0_orchestrator/test_suite/framework/orchestrator_driver.py
tests/0_orchestrator/test_suite/requirements.txt
tests/0_orchestrator/test_suite/testcases/basic_tests/test07_vms_apis.py
tests/0_orchestrator/test_suite/testcases/testcases_base.py

fixes https://github.com/zero-os/0-orchestrator/issues/1168

execute bash commands on vm 

---

tests/0_orchestrator/test_suite/testcases/basic_tests/test07_vms_apis.py

fixes https://github.com/zero-os/0-orchestrator/issues/1169

start vm after shutdown and execute command on it

---

templates/container/actions.py
templates/etcd/actions.py

added a schedule run to handle multiple failures

---

tests/0_orchestrator/test_suite/testcases/basic_tests/test04_storageclusters_apis.py

fixes https://github.com/zero-os/0-orchestrator/issues/1263

cover delete storagecluster which has vdiskstorage

---

pyclient/zeroos/orchestrator/sal/Container.py
templates/etcd_cluster/actions.py

adjusted the watchdoghandler of etcdcluster to be async

---

api/node/FtpInfo.go

support anonymous ftp servers in import vm

---

api/node/ImportVM.go
api/node/node_api_ImportVM.go
api/node/node_if.go
raml/api.html
raml/api.raml
raml/types.raml
templates/vdisk/actions.py

move imported vmid to payload

---

pyclient/zeroos/orchestrator/client/Cluster.py
pyclient/zeroos/orchestrator/client/ExportVM.py
pyclient/zeroos/orchestrator/client/FTPUrl.py
pyclient/zeroos/orchestrator/client/MigrateGW.py
pyclient/zeroos/orchestrator/client/__init__.py
pyclient/zeroos/orchestrator/client/nodes_service.py

generate pyclient

---

pyclient/zeroos/orchestrator/sal/StoragePool.py
templates/filesystem/actions.py

Fixing quota

---

api/node/node_api_DeleteNode.go
api/vdiskstorage/vdiskstorage_api_DeleteVdiskStorage.go

Related to https://github.com/zero-os/0-orchestrator/issues/912

nodes with storage components can't be deleted

---

api/ays-client/Service.go
api/storagecluster/storageclusters_api_GetClusterInfo.go
api/storagecluster/storageclusters_api_KillCluster.go

Add actor to service struct

---

tests/0_orchestrator/test_suite/framework/orchestrator_apis/graphs_apis.py
tests/0_orchestrator/test_suite/framework/orchestrator_driver.py
tests/0_orchestrator/test_suite/testcases/basic_tests/test12_graphs_apis.py
tests/0_orchestrator/test_suite/testcases/testcases_base.py

fixes https://github.com/zero-os/0-orchestrator/issues/1292

Graph apis tests

---

tests/0_orchestrator/test_suite/testcases/basic_tests/test06_vdisks_apis.py
tests/0_orchestrator/test_suite/testcases/basic_tests/test07_vms_apis.py
tests/0_orchestrator/test_suite/testcases/basic_tests/test11_vdisks_apis_ext.py

fixes https://github.com/zero-os/0-orchestrator/issues/1299

delete vdiskstorage in teardowns

---

api/graph/GraphUpdate.go
api/graph/graph_api_GetDashboard.go
api/graph/graph_api_ListGraphs.go
api/graph/graph_api_UpdateGraph.go
raml/api.html
raml/api.raml
raml/types.raml
templates/dashboard/actions.py
templates/grafana/actions.py

Fixes:
- https://github.com/zero-os/0-orchestrator/issues/1314
- https://github.com/zero-os/0-orchestrator/issues/1312
- https://github.com/zero-os/0-orchestrator/issues/1311
- https://github.com/zero-os/0-orchestrator/issues/1310

Graph API  Fixes

---

api/healthcheck/health_api_Nodes.go
raml/api.html
raml/api.raml
raml/types.raml
templates/node.zero-os/actions.py

Fixes https://github.com/zero-os/0-orchestrator/issues/1332

Healthcheck skipped

---

templates/filesystem/actions.py

ignore error in deleting filesystem if pool was not found

---

templates/storagecluster.block/actions.py
templates/storagecluster.object/actions.py
templates/tlogserver/actions.py
templates/vdisk/actions.py
templates/vdisk_image/actions.py

update create and import of vdisk to match the latest 0-disk changes

---

api/tools/runs.go
api/vdiskstorage/ImageImport.go
api/vdiskstorage/vdisk/VdiskCreate.go
api/vdiskstorage/vdisk/vdisk_api_CreateNewVdisk.go
api/vdiskstorage/vdiskstorage_api_ImportImage.go
pyclient/zeroos/orchestrator/client/GraphUpdate.py
pyclient/zeroos/orchestrator/client/ImageImport.py
pyclient/zeroos/orchestrator/client/__init__.py
pyclient/zeroos/orchestrator/utils.py
raml/api.html
raml/types.raml
templates/storagecluster.block/actions.py
templates/vdisk_image/actions.py

 use zeroctl describe to get image size and exportblocksize 

---

api/graph/graph_api_ListDashboards.go

Fixes https://github.com/zero-os/0-orchestrator/issues/1312

Check if graph exists in listdashboards

---

api/vdiskstorage/vdisk/vdisk_api_CreateNewVdisk.go
pyclient/zeroos/orchestrator/utils.py
templates/vdisk_image/actions.py

update import image to use the latest zeroctl describe output

---

scripts/install-orchestrator.sh

Fixes: https://github.com/zero-os/0-orchestrator/issues/1370

Fixes to support running on top of js9.3

---

docs/setup/README.md
scripts/install-orchestrator.sh

Fixes: https://github.com/zero-os/0-orchestrator/issues/1372

fix installer and update docs
